// Post-build prerendering: turns every client-side route into a real HTML file.
//
// WHY THIS EXISTS
// This is a client-rendered SPA on GitHub Pages, so before this script every deep link was
// served by public/404.html — verified against production on 2026-08-26:
//
//   $ curl -sI .../portfolio/blog/grpc-service-mesh-in-go-aegis-architecture
//   HTTP/2 404
//   $ curl -s  .../portfolio/blog/grpc-service-mesh-in-go-aegis-architecture | grep '<title>'
//   <title>Redirecting…</title>
//
// 51 of the 52 URLs in sitemap.xml answered 404 with no description, no canonical and no
// og:image. Every one of the 33 OG images generated by build-search-index.mjs was therefore
// dead weight: social crawlers don't run JavaScript, so sharing an article anywhere produced
// a blank, title-less card, and the site was effectively one indexable page.
//
// APPROACH — snapshot, not SSR
// Load each route in headless Chromium and serialize the rendered DOM. The alternative,
// react-dom/server, would need StaticRouter, an SSR-safe replacement for useSeo's imperative
// document.head mutation, Node-side handling of content-index.ts's runtime fetch(), and a
// browser shim for mermaid — i.e. rewriting the content engine, which .ai/decision-log.md
// Decision 1 and the constitution both require an explicit ADR for. Snapshotting gets the
// full SEO and social benefit with no change to the app.
//
// Because useSeo has already written the correct <title>/description/canonical/og:* by the
// time the page settles, per-route metadata comes out right for free. Each snapshot still
// ships the original module scripts, so the page boots and behaves as a normal SPA after
// first paint. React 18's createRoot discards the pre-rendered children rather than
// hydrating them — that is intended: the markup is byte-identical, and MarkdownContent's
// DOM-mutation passes (copy buttons, figures, status marks) would mismatch under
// hydrateRoot. See the plan's Batch 2 notes.
//
// OUTPUT SHAPE
// `<route>.html`, not `<route>/index.html`. GitHub Pages resolves an extensionless request
// to the sibling .html file with a 200 and no redirect (verified: /portfolio/404 -> 200),
// so existing canonical URLs and sitemap entries need no trailing-slash change.

import { createServer } from 'node:http';
import { readFile, mkdir, writeFile, stat } from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright';
import { basePath, origin as publicOrigin, siteUrl } from '../site.config.mjs';
import { labIds, readArticleRoutes, staticRoutes } from './lib/site-routes.mjs';

// Snapshots are taken with the colour scheme forced to light so the serialized <html> never
// carries a `dark` class. The theme is a per-visitor preference, and the inline bootstrap in
// index.html applies it before first paint — baking the build machine's preference into 54 static
// files would serve every visitor whichever theme the CI runner happened to have.
const distDir = path.join(process.cwd(), 'dist');
const CONCURRENCY = 4;
const NAV_TIMEOUT_MS = 30_000;
const SETTLE_TIMEOUT_MS = 20_000;

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.ico': 'image/x-icon',
  '.xml': 'application/xml; charset=utf-8',
  '.txt': 'text/plain; charset=utf-8',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
};

/**
 * Serves dist/ under basePath with an index.html fallback.
 *
 * Deliberately not `vite preview`: the CI workflow already has to background that process in
 * its own step and poll it with a 30x curl loop because the shell orphans it, and --strictPort
 * makes a port collision a hard failure. An in-process server has no orphan, no port race, and
 * shuts down with the script.
 */
async function startServer() {
  const server = createServer(async (req, res) => {
    let pathname;
    try {
      pathname = decodeURIComponent(new URL(req.url, 'http://localhost').pathname);
    } catch {
      res.writeHead(400).end();
      return;
    }

    // Strip the base path; anything outside it is not ours to serve.
    if (!pathname.startsWith(basePath)) {
      res.writeHead(404).end();
      return;
    }
    const relative = pathname.slice(basePath.length);

    // Resolve inside dist/ only — refuse anything that escapes via `..`.
    const candidate = path.resolve(distDir, relative);
    if (candidate !== distDir && !candidate.startsWith(distDir + path.sep)) {
      res.writeHead(403).end();
      return;
    }

    for (const target of [candidate, `${candidate}.html`, path.join(candidate, 'index.html')]) {
      try {
        if (!(await stat(target)).isFile()) continue;
        const body = await readFile(target);
        res.writeHead(200, { 'content-type': MIME[path.extname(target)] ?? 'application/octet-stream' });
        res.end(body);
        return;
      } catch {
        // try the next candidate
      }
    }

    // SPA fallback: unknown paths get the app shell so client-side routing can resolve them.
    // This is what lets the very first prerender pass work before any route file exists.
    res.writeHead(200, { 'content-type': MIME['.html'] });
    res.end(await readFile(path.join(distDir, 'index.html')));
  });

  await new Promise((resolve, reject) => {
    server.once('error', reject);
    server.listen(0, '127.0.0.1', resolve);
  });

  const { port } = server.address();
  return { server, origin: `http://127.0.0.1:${port}` };
}

/** dist-relative output file for a route. '/' -> index.html, '/blog/x' -> blog/x.html */
function outputPathFor(route) {
  if (route === '/') return path.join(distDir, 'index.html');
  return path.join(distDir, `${route.replace(/^\//, '')}.html`);
}

/**
 * Waits until the route has actually finished rendering, so the snapshot isn't a spinner.
 *
 * Three separate conditions, because each one has bitten a different route shape:
 *  - #root has real children (the app mounted at all);
 *  - no LoadingState is on screen (role="status" — article pages fetch the index, then the
 *    raw markdown, then dynamically import the markdown compiler);
 *  - every .mermaid-diagram has reached .mermaid-rendered (mermaid renders async well after
 *    mount, and an unrendered diagram serializes as an empty skeleton box).
 */
async function waitForRender(page) {
  await page.waitForFunction(
    () => {
      const root = document.getElementById('root');
      if (!root || root.children.length === 0) return false;
      if (document.querySelector('[role="status"]')) return false;
      const diagrams = [...document.querySelectorAll('.mermaid-diagram')];
      return diagrams.every((el) => el.classList.contains('mermaid-rendered'));
    },
    undefined,
    { timeout: SETTLE_TIMEOUT_MS }
  );
}

/**
 * Asserts the snapshot is actually worth serving. These throw rather than warn on purpose:
 * a page that prerenders without its own metadata is the exact silent failure this whole
 * script exists to fix, and build-search-index.mjs already sets the precedent of failing the
 * build on a bad `related:` reference rather than emitting something subtly broken.
 */
function validate(route, html, shellTitle) {
  const problems = [];

  const title = html.match(/<title>([\s\S]*?)<\/title>/)?.[1]?.trim();
  if (!title) problems.push('no <title>');
  else if (route !== '/' && title === shellTitle) problems.push(`title is still the shell default (${title})`);

  const canonical = html.match(/<link[^>]+rel="canonical"[^>]+href="([^"]+)"/)?.[1];
  const expected = `${siteUrl}${route === '/' ? '/' : route}`;
  if (!canonical) problems.push('no rel=canonical');
  else if (canonical.replace(/\/$/, '') !== expected.replace(/\/$/, '')) {
    problems.push(`canonical is ${canonical}, expected ${expected}`);
  }

  if (!/<meta[^>]+property="og:image"/.test(html)) problems.push('no og:image');
  if (!/<meta[^>]+name="description"/.test(html)) problems.push('no meta description');
  if (html.includes('mermaid-error')) problems.push('page contains a mermaid-error box');

  return problems;
}

/**
 * The old /experiments/<labId> paths, which App.tsx serves as client-side <Navigate>
 * redirects. A <Navigate> snapshot would be the lab page's markup living at the article's
 * URL, so these get a real redirect document instead — canonical plus meta refresh, which
 * non-JS clients and crawlers both understand.
 *
 * Which ids redirect is derived, not duplicated: registry.ts flags an id
 * `collidesWithArticleSlug` exactly when /experiments/<id> is also a real article, and that
 * is observable from the article route list. So this stays correct automatically when a lab
 * or article is added.
 */
function redirectRoutes(articleRoutes) {
  const articles = new Set(articleRoutes);
  return labIds
    .filter((id) => !articles.has(`/experiments/${id}`))
    .map((id) => ({ from: `/experiments/${id}`, to: `/labs/${id}` }));
}

function redirectHtml({ from, to }) {
  const target = `${basePath}${to.replace(/^\//, '')}`;
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <!-- Generated by scripts/prerender.mjs. ${from} moved to ${to} (see .ai/decision-log.md
         Decision 5); App.tsx also handles this client-side via <Navigate replace>. This static
         copy exists so crawlers and non-JS clients follow the move too. -->
    <title>Redirecting to ${to}</title>
    <link rel="canonical" href="${siteUrl}${to}" />
    <meta name="robots" content="noindex, follow" />
    <meta http-equiv="refresh" content="0; url=${target}" />
  </head>
  <body>
    <p>This page moved to <a href="${target}">${to}</a>.</p>
    <script>location.replace(${JSON.stringify(target)});</script>
  </body>
</html>
`;
}

/**
 * Every absolute URL in a snapshot is built at runtime from window.location.origin —
 * useSeo does it for canonical/og:url/og:image/twitter:image and the two feed links, and
 * ContentDetailPage does it again independently for the JSON-LD url/@id. Serialized as-is,
 * that would ship `http://127.0.0.1:<port>/...` inside every deployed page: canonical tags
 * pointing at localhost are worse than the 404s this script is fixing. So the local origin is
 * rewritten to the real one before anything is validated or written.
 */
function rewriteOrigin(html, serverOrigin) {
  return html.split(serverOrigin).join(publicOrigin);
}

async function renderRoute(page, serverOrigin, route) {
  const consoleErrors = [];
  const onConsole = (msg) => {
    if (msg.type() === 'error') consoleErrors.push(msg.text());
  };
  page.on('console', onConsole);

  try {
    const url = `${serverOrigin}${basePath}${route.replace(/^\//, '')}`;
    const response = await page.goto(url, { waitUntil: 'networkidle', timeout: NAV_TIMEOUT_MS });
    if (!response?.ok()) throw new Error(`navigation returned ${response?.status()}`);
    await waitForRender(page);
    const serialized = await page.evaluate(() => document.documentElement.outerHTML);
    const html = rewriteOrigin(`<!doctype html>\n${serialized}`, serverOrigin);

    // Checks for the exact server origin (scheme + IP + port), not the bare "127.0.0.1" substring —
    // an article can legitimately mention that IP in its own prose (see
    // content/blog/2026-08-27-the-spa-google-never-saw.md, which explains this very mechanism) without
    // that being a real leak. Only the literal, port-qualified origin the rewrite operates on proves one.
    if (html.includes(serverOrigin)) {
      throw new Error(`snapshot still contains the local server origin (${serverOrigin}) after rewrite`);
    }
    if (/<html[^>]*\bclass="[^"]*\bdark\b/.test(html)) {
      throw new Error('snapshot baked in the dark theme — see the colorScheme note above');
    }

    return { html, consoleErrors };
  } finally {
    page.off('console', onConsole);
  }
}

async function main() {
  const articleRoutes = readArticleRoutes('prerender');
  if (articleRoutes.length === 0) {
    throw new Error(
      'No article routes found. public/content-index.json is missing or empty — run ' +
        '`npm run build:search-index` before prerendering.'
    );
  }

  // /search is prerendered even though it is deliberately absent from the sitemap: it renders
  // an empty search UI with no content to index, but it still needs a real file to exist now
  // that 404.html no longer redirects unknown paths back into the SPA.
  const routes = [...staticRoutes, '/search', ...articleRoutes];
  const redirects = redirectRoutes(articleRoutes);

  const { server, origin } = await startServer();
  const browser = await chromium.launch();

  const shellTitle = (await readFile(path.join(distDir, 'index.html'), 'utf8'))
    .match(/<title>([\s\S]*?)<\/title>/)?.[1]
    ?.trim();

  const failures = [];
  const written = [];
  let cursor = 0;

  const worker = async () => {
    const page = await browser.newPage({ viewport: { width: 1280, height: 900 }, colorScheme: 'light' });
    try {
      while (cursor < routes.length) {
        const route = routes[cursor++];
        try {
          const { html, consoleErrors } = await renderRoute(page, origin, route);
          const problems = validate(route, html, shellTitle);
          if (consoleErrors.length > 0) problems.push(`console error: ${consoleErrors[0]}`);
          if (problems.length > 0) {
            failures.push(`${route} — ${problems.join('; ')}`);
            continue;
          }
          const out = outputPathFor(route);
          await mkdir(path.dirname(out), { recursive: true });
          await writeFile(out, html, 'utf8');
          written.push({ route, bytes: Buffer.byteLength(html) });
        } catch (error) {
          failures.push(`${route} — ${error.message}`);
        }
      }
    } finally {
      await page.close();
    }
  };

  console.log(`[prerender] ${routes.length} routes + ${redirects.length} redirect stubs`);
  await Promise.all(Array.from({ length: Math.min(CONCURRENCY, routes.length) }, worker));

  // The 404 page is rendered last and from a path we know is not a real route, so GitHub Pages
  // still has something correct to serve for a genuinely wrong URL. It replaces the old
  // ?redirect= bootstrap in public/404.html: now that every real route is a real file, an
  // unknown path is a true 404 and should look like one instead of bouncing through the SPA.
  {
    const page = await browser.newPage({ viewport: { width: 1280, height: 900 }, colorScheme: 'light' });
    try {
      const { html } = await renderRoute(page, origin, '/this-route-does-not-exist');
      await writeFile(path.join(distDir, '404.html'), html, 'utf8');
      written.push({ route: '404.html', bytes: Buffer.byteLength(html) });
    } finally {
      await page.close();
    }
  }

  for (const redirect of redirects) {
    const out = outputPathFor(redirect.from);
    await mkdir(path.dirname(out), { recursive: true });
    await writeFile(out, redirectHtml(redirect), 'utf8');
  }

  await browser.close();
  await new Promise((resolve) => server.close(resolve));

  if (failures.length > 0) {
    console.error(`\n[prerender] FAILED — ${failures.length} route(s):`);
    for (const failure of failures) console.error(`  ${failure}`);
    process.exit(1);
  }

  const total = written.reduce((sum, w) => sum + w.bytes, 0);
  const largest = [...written].sort((a, b) => b.bytes - a.bytes).slice(0, 3);
  console.log(
    `[prerender] PASS — ${written.length} pages + ${redirects.length} redirects, ` +
      `${(total / 1024 / 1024).toFixed(2)} MB total`
  );
  console.log(
    `[prerender] largest: ${largest.map((w) => `${w.route} ${(w.bytes / 1024).toFixed(0)} KB`).join(', ')}`
  );
}

main().catch((error) => {
  console.error(`[prerender] ${error.stack ?? error.message}`);
  process.exit(1);
});
